[package]
name = "denoise_exr"
version = "0.1.0"
authors = ["Will Usher <will@willusher.io>"]

[dependencies]
oidn = { path = "../../" }
image = "0.22.5"
exr = "0.9.0"
docopt = "1.1.0"
rayon = "1.4.0"
serde = { version = "1.0.115", features = ["derive"] }
