[package]
name = "oidn"
version = "1.2.0"
authors = ["Will Usher <will@willusher.io>"]
build = "build.rs"
homepage = "https://github.com/Twinklebear/oidn-rs"
documentation = "http://www.willusher.io/oidn-rs/oidn/"
repository = "https://github.com/Twinklebear/oidn-rs"
readme = "README.md"
license = "MIT"
description = """
A wrapper for the Intel OpenImageDenoise image denoising library.
"""
keywords = ["openimagedenoise", "denoise", "denoising"]
exclude = [
    ".travis.yml",
    "*.png",
    "*.jpg",
    ".gitignore",
    "examples/*"
]

